### PR TITLE
Use ad-hoc extension comparison to avoid initialization issues

### PR DESCRIPTION
**Pull request by pdimov**
Alternative to #43 and #59.

### CODE REVIEW

**Comment by DanielaE** [comment]
Simple as it is, it is fine with me. 👍

**Comment by pdimov** [comment]
Would also supersede #50.

**Comment by DanielaE** [comment]
This problem seems to have been discovered over and over again 😄

**Comment by Dani-Hub** [comment]
I vote for your revised patch and withdraw my further revised patch https://github.com/Dani-Hub/filesystem/commit/76c061ec79328cc4fee6a23f07e2918c66fe44a7 and https://github.com/Dani-Hub/filesystem/commit/63d758789fa102a9be1741522d6f5d232e39ce4e. If the future shows a proper need for my icase correct code, we can restore and refine it further. For now I keep it in my private code where I have practical uses for it.

**Comment by pdimov** [comment]
Thanks Daniel. Just need @Beman's blessing then.

**Pull request merged**
