### PR TITLE
Universal windows

### PR DESCRIPTION
**Pull request by mauve**
Add support for Universal Windows Platform

### CODE REVIEW

**Comment by SimmonsTech** [comment]
I've tried merging this in and testing - but a number of APIs don't seem to be available in Win10 on a boost cli build. Building with: toolset=msvc-14.0 link=static windows-api=store

Notably: GetFullPathName, GetCurrentDirectory etc.

**Comment by mauve** [comment]
@SimmonsTech I just rebased on develop and repushed, I also compiled it again locally and it compiles cleanly for me. You however need to have the Windows 10 SDK installed, according to `C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\um\fileapi.h` GetFullPathName is available, that is however not the case with the windows 8.1 SDK (where it is only available in the desktop api partition).

**Comment by SimmonsTech** [comment]
Interesting, I do indeed have the Win10 SDK installed but still see these issues. I'll have another dig. You are using the same CLI arguments?

**Comment by mauve** [comment]
~\DEV\other-repositories\boost\libs\filesystem [universal-windows] > git lg -1
    * d8b015a - (HEAD -> universal-windows) universal-windows: Add missing boost.predef includes (43 minutes ago) <Mikael Olenfalk>
    ~\DEV\other-repositories\boost\libs\filesystem [universal-windows] > cd .\build\
    ~\DEV\other-repositories\boost\libs\filesystem\build [universal-windows] > rm -recurse -force ..\..\..\bin.v2\
    ~\DEV\other-repositories\boost\libs\filesystem\build [universal-windows] > ..\..\..\b2.exe toolset=msvc-14.0 link=static windows-api=store
    Performing configuration checks

        - 32-bit                   : yes
        - arm                      : no
        - mips1                    : no
        - power                    : no
        - sparc                    : no
        - x86                      : yes
        - symlinks supported       : no
        - junctions supported      : yes
        - hardlinks supported      : yes
    ...patience...
    ...found 1266 targets...
    ...updating 17 targets...
    common.mkdir ..\..\..\bin.v2\libs
    common.mkdir ..\..\..\bin.v2\libs\filesystem
    common.mkdir ..\..\..\bin.v2\libs\filesystem\build
    common.mkdir ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0
    common.mkdir ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug
    common.mkdir ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static
    common.mkdir ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi
    common.mkdir ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\codecvt_error_category.obj
    codecvt_error_category.cpp
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\operations.obj
    operations.cpp
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\path.obj
    path.cpp
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\path_traits.obj
    path_traits.cpp
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\portability.obj
    portability.cpp
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\unique_path.obj
    unique_path.cpp
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\utf8_codecvt_facet.obj
    utf8_codecvt_facet.cpp
    compile-c-c++ ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\windows_file_codecvt.obj
    windows_file_codecvt.cpp
    msvc.archive ..\..\..\bin.v2\libs\filesystem\build\msvc-14.0\debug\link-static\threading-multi\windows-api-store\libboost_filesystem-vc140-mt-gd-1_59.lib
    ...updated 17 targets...
    ~\DEV\other-repositories\boost\libs\filesystem\build [universal-windows] >

**Comment by Orphis** [comment]
@mauve @StSimmons Any update on this PR? Boost 1.61.0 b1 still doesn't build for WindowsStore.

**Comment by mauve** [comment]
@Orphis what are you trying to build? I haven't tried in a while but can give it a go this weekend.

**Comment by Orphis** [comment]
Nothing, you know. Just the Boost filesystem lib for WindowsStore platforms!

**Comment by fxb** [comment]
@Beman: It would be nice to also get this pull request merged to make Boost.Filesystem compile for the Universal Windows Platform.

I rebased @mauve's changes on latest develop and they compile and work fine.

If you have any comments or suggestions on these changes, I'll be happy to look at those.

**Comment by zdunker** [comment]
Really need UWP filesystem lib!

**Comment by crule42** [comment]
I needed this patch also, so I made the changes on top of the latest release build 1.69.0 as of this writing (not master or develop). Here is the patch in case others want it also.


[0001-Implemented-changes-from-PR-18-on-top-of-the-latest-.zip](https://github.com/boostorg/filesystem/files/2747512/0001-Implemented-changes-from-PR-18-on-top-of-the-latest-.zip)

**Comment by Lastique** [comment]
If this is still relevant, please rebase against the current develop.

**Comment by soroshsabz** [comment]
@mauve Did you want to update this PR?

**Comment by Lastique** [comment]
Closing as the PR is inactive.

**Pull request closed without merging**
