### PR TITLE
Correct handling of status() for reparse point when it is not a symlink.

### PR DESCRIPTION
**Pull request by stima**
When the path is Windows Reparse Point and it is not a symlink return status as reparse_file, otherwise resolve symlink and return status as regural_file with attributes of resolved file.

### CODE REVIEW

**Comment by stima** [comment]
Hello guys, is the any changes to have it reviewed and committed?

**Comment by stima** [comment]
Hi guys, any updates?

**Comment by Flamefire** [comment]
As I'm working on something related: What exactly is the problem you fixed here? Do you have a testcase that fails? Can you add that to the tests?

**Comment by stima** [comment]
Hi. I will create test soon.

**Pull request closed without merging**
